### ISSUE TITLE
Support VER AMX?

### ISSUE THREAD

**Issue by Soyrce** [raheem-cs/Zombie-Escape#1]
Hey can you please tell me what he support 1.9.0 or 1.8.3 AMXX?
and update your github with sound/models zombie ?

**Comment by mohammed-alaa** [comment]
The mod works for both v1.8.3 & v1.9.0. However, it's recommended to use v1.9.0.
You can download the resources from: [https://escapers-zone.net/viewtopic.php?f=6&t=6](https://escapers-zone.net/viewtopic.php?f=6&t=6)
Take time to visit: [https://escapers-zone.net](https://escapers-zone.net)

**Comment by Soyrce** [comment]
> The mod works for both v1.8.3 & v1.9.0. However, it's recommended to use v1.9.0.
> You can download the resources from: https://escapers-zone.net/viewtopic.php?f=6&t=6
> Take time to visit: https://escapers-zone.net

okay is it wont work on 
AMX Mod X 1.8.2?

**Comment by Soyrce** [comment]
> The mod works for both v1.8.3 & v1.9.0. However, it's recommended to use v1.9.0.
> You can download the resources from: https://escapers-zone.net/viewtopic.php?f=6&t=6
> Take time to visit: https://escapers-zone.net

![image](https://user-images.githubusercontent.com/34108561/66567841-bfe79300-eb70-11e9-92a4-b477bc5c4ebb.png)
why is not working?

**Comment by mohammed-alaa** [comment]
I can't figure the issue out from the photo. Please, provide more information from logs, debug, etc.. so we can help you to fix this issue.
Edit: Make sure that the online players are equal or more than the "ze_required_players" cvar value.
